export const STORAGE_KEYS = {
  authToken: "tourisk:authToken",
  user: "tourisk:user",
  checkins: "tourisk:checkins",
  visitedCells: "tourisk:visitedCells",
  openedLegendaryPlaces: "tourisk:openedLegendaryPlaces",
  locationTrail: "tourisk:locationTrail",
  totalDistanceMeters: "tourisk:totalDistanceMeters",
  lastDistancePoint: "tourisk:lastDistancePoint",
  streakDays: "tourisk:streakDays",
  lastActiveDate: "tourisk:lastActiveDate",
  hasSeenIntro: "tourisk:hasSeenIntro",
  gameContent: "tourisk:gameContent",
  dailyJourneys: "tourisk:dailyJourneys",
  dailyJourneyLastShown: "tourisk:dailyJourneyLastShown",
};
