export const DEFAULT_ACHIEVEMENTS = [
  { id: "first_step", title: "Первый шаг", description: "Открыть первую территорию", icon: "✦", conditionType: "cells", conditionValue: 1, rewardXp: 20, sortOrder: 10 },
  { id: "distance_10", title: "Первые 10 км", description: "Пройти 10 километров", icon: "🥾", conditionType: "distanceKm", conditionValue: 10, rewardXp: 100, sortOrder: 20 },
  { id: "legendary_5", title: "Хранитель легенд", description: "Открыть 5 легендарных мест", icon: "🏛️", conditionType: "legendaryPlaces", conditionValue: 5, rewardXp: 250, sortOrder: 30 },
  { id: "area_100", title: "Картограф", description: "Исследовать 100 км² территории", icon: "🗺️", conditionType: "exploredKm2", conditionValue: 100, rewardXp: 500, sortOrder: 40 },
  { id: "yerevan_all", title: "Сердце Еревана", description: "Открыть все места Еревана", icon: "🇦🇲", conditionType: "yerevanPlaces", conditionValue: 10, rewardXp: 700, sortOrder: 50 },
  { id: "distance_100", title: "Дальняя дорога", description: "Пройти 100 километров", icon: "🧭", conditionType: "distanceKm", conditionValue: 100, rewardXp: 800, sortOrder: 60 },
  { id: "hidden_5", title: "Тайный след", description: "Найти 5 скрытых мест", icon: "🔮", conditionType: "hiddenPlaces", conditionValue: 5, rewardXp: 450, sortOrder: 70 },
  { id: "yerevan_10_percent", title: "Десятая часть", description: "Исследовать 10% Еревана", icon: "🌆", conditionType: "yerevanPercent", conditionValue: 10, rewardXp: 300, sortOrder: 80 },
  { id: "stars_1000", title: "Звёздный путь", description: "Собрать 1000 звёзд", icon: "⭐", conditionType: "stars", conditionValue: 1000, rewardXp: 600, sortOrder: 90 },
  { id: "streak_7", title: "Семь рассветов", description: "Заходить 7 дней подряд", icon: "🔥", conditionType: "streakDays", conditionValue: 7, rewardXp: 350, sortOrder: 100 },
  { id: "first_country", title: "За границей карты", description: "Открыть первую страну", icon: "🌍", conditionType: "countries", conditionValue: 1, rewardXp: 70, sortOrder: 110 },
  { id: "five_cities", title: "Городской маршрут", description: "Открыть 5 городов", icon: "🏙️", conditionType: "cities", conditionValue: 5, rewardXp: 220, sortOrder: 120 },
  { id: "territories_50", title: "Первопроходец", description: "Открыть 50 территорий", icon: "🏆", conditionType: "cells", conditionValue: 50, rewardXp: 200, sortOrder: 130 },
];

export const DEFAULT_PAWNS = [
  { id: "pawn_green", name: "Росток", rarity: "common", imagePath: "/uploads/pawns/pawn_green_v14.png", condition: "Доступна сразу", unlockType: "level", unlockValue: 1, sortOrder: 10, glowColor: "#a9ec56", mapScale: 1 },
  { id: "pawn_bronze", name: "Следопыт", rarity: "uncommon", imagePath: "/uploads/pawns/pawn_bronze_v14.png", condition: "Пройди 10 км", unlockType: "distanceKm", unlockValue: 10, sortOrder: 20, glowColor: "#d88c48", mapScale: 1 },
  { id: "pawn_silver", name: "Хранитель", rarity: "rare", imagePath: "/uploads/pawns/pawn_silver_v14.png", condition: "Получи 3 достижения", unlockType: "achievements", unlockValue: 3, sortOrder: 30, glowColor: "#68d6ff", mapScale: 1 },
  { id: "pawn_gold", name: "Солнечный", rarity: "legendary", imagePath: "/uploads/pawns/pawn_gold_v14.png", condition: "Собери 1000 звёзд", unlockType: "stars", unlockValue: 1000, sortOrder: 40, glowColor: "#f4c451", mapScale: 1.04 },
  { id: "pawn_azure", name: "Небесный", rarity: "rare", imagePath: "/uploads/pawns/pawn_azure_v14.png", condition: "Исследуй 100 км²", unlockType: "exploredKm2", unlockValue: 100, sortOrder: 50, glowColor: "#68d6ff", mapScale: 1 },
  { id: "pawn_violet", name: "Сумеречный", rarity: "epic", imagePath: "/uploads/pawns/pawn_violet_v14.png", condition: "Открой 10% Еревана", unlockType: "yerevanPercent", unlockValue: 10, sortOrder: 60, glowColor: "#c66dff", mapScale: 1 },
  { id: "pawn_ember", name: "Пламенный", rarity: "epic", imagePath: "/uploads/pawns/pawn_ember_v14.png", condition: "Пройди 100 км", unlockType: "distanceKm", unlockValue: 100, sortOrder: 70, glowColor: "#ff6c45", mapScale: 1 },
  { id: "pawn_crystal", name: "Кристалл", rarity: "legendary", imagePath: "/uploads/pawns/pawn_crystal_v14.png", condition: "Открой 5 легендарных мест", unlockType: "legendaryPlaces", unlockValue: 5, sortOrder: 80, glowColor: "#78ffd4", mapScale: 1.05 },
  { id: "pawn_shadow", name: "Тень", rarity: "shadow", imagePath: "/uploads/pawns/pawn_shadow_v14.png", condition: "Найди 5 скрытых мест", unlockType: "hiddenPlaces", unlockValue: 5, sortOrder: 90, glowColor: "#8d72d8", mapScale: 1 },
  { id: "pawn_aurora", name: "Аврора", rarity: "mythic", imagePath: "/uploads/pawns/pawn_aurora_v14.png", condition: "Заходи 7 дней подряд", unlockType: "streakDays", unlockValue: 7, sortOrder: 100, glowColor: "#78ffd4", mapScale: 1.05 },
];

export const DEFAULT_PLACES = [
  {
    id: "cascade",
    name: "Каскад",
    icon: "🏛",
    description: "Ты поднялся туда, где Ереван открывается как на ладони.\n\nКаждый шаг наверх приближает тебя к городу, который теперь стал частью твоей истории.",
    city: "Ереван",
    country: "Армения",
    latitude: 40.19055,
    longitude: 44.51555,
    rarity: "legendary",
    xp: 50,
    discoveryRadiusMeters: 320,
    imagePath: "/uploads/places/cascade.jpg",
    sortOrder: 10,
  },
  {
    id: "republic_square",
    name: "Площадь Республики",
    icon: "🏛",
    description: "Сердце Еревана теперь бьётся и в твоём пути.\n\nЗдесь встречаются тысячи людей, но именно сегодня это место стало частью твоего мира.",
    city: "Ереван",
    country: "Армения",
    latitude: 40.1776,
    longitude: 44.5126,
    rarity: "legendary",
    xp: 50,
    discoveryRadiusMeters: 300,
    imagePath: "/uploads/places/republic-square.jpg",
    sortOrder: 20,
  },
  {
    id: "opera_theatre",
    name: "Оперный театр",
    icon: "🎭",
    description: "Город умеет говорить не только улицами, но и искусством.\n\nСегодня ты открыл одно из мест, где уже десятилетиями рождаются эмоции.",
    city: "Ереван",
    country: "Армения",
    latitude: 40.1867,
    longitude: 44.5145,
    rarity: "legendary",
    xp: 50,
    discoveryRadiusMeters: 280,
    imagePath: "/uploads/places/opera-theatre.jpg",
    sortOrder: 30,
  },
  {
    id: "mother_armenia",
    name: "Мать Армения",
    icon: "🗿",
    description: "Отсюда город кажется бесконечным, а твой путь — только начинается.\n\nТеперь ты увидел Ереван с высоты исследователя.",
    city: "Ереван",
    country: "Армения",
    latitude: 40.1953,
    longitude: 44.5241,
    rarity: "legendary",
    xp: 50,
    discoveryRadiusMeters: 240,
    imagePath: "/uploads/places/mother-armenia.jpg",
    sortOrder: 40,
  },
  {
    id: "matenadaran",
    name: "Матенадаран",
    icon: "📚",
    description: "Некоторые сокровища хранят знания, другие — воспоминания.\n\nСегодня ты прикоснулся к одному из символов человеческой памяти.",
    city: "Ереван",
    country: "Армения",
    latitude: 40.1912,
    longitude: 44.5213,
    rarity: "legendary",
    xp: 50,
    discoveryRadiusMeters: 220,
    imagePath: "/uploads/places/matenadaran.jpg",
    sortOrder: 50,
  },
  {
    id: "saryan_street",
    name: "Улица Саряна",
    icon: "🌇",
    description: "Здесь Ереван становится медленнее.\n\nЗапах кофе, разговоры и вечерний свет теперь навсегда останутся в твоём следе.",
    city: "Ереван",
    country: "Армения",
    latitude: 40.1848,
    longitude: 44.5084,
    rarity: "legendary",
    xp: 50,
    discoveryRadiusMeters: 190,
    imagePath: "/uploads/places/saryan-street.jpg",
    sortOrder: 60,
  },
  {
    id: "lovers_park",
    name: "Парк влюблённых",
    icon: "🌳",
    description: "Иногда открытие — это не вершина горы, а несколько минут спокойствия.\n\nТы нашёл место, где город делает глубокий вдох.",
    city: "Ереван",
    country: "Армения",
    latitude: 40.1912,
    longitude: 44.5066,
    rarity: "legendary",
    xp: 50,
    discoveryRadiusMeters: 190,
    imagePath: "/uploads/places/lovers-park.jpg",
    sortOrder: 70,
  },
  {
    id: "tsitsernakaberd",
    name: "Цицернакаберд",
    icon: "🕊",
    description: "Есть места, где важно не спешить.\n\nСегодня ты посетил место памяти, которое напоминает, насколько ценен каждый человеческий путь.",
    city: "Ереван",
    country: "Армения",
    latitude: 40.1858,
    longitude: 44.4906,
    rarity: "legendary",
    xp: 50,
    discoveryRadiusMeters: 250,
    imagePath: "/uploads/places/tsitsernakaberd.jpg",
    sortOrder: 80,
  },
  {
    id: "blue_mosque",
    name: "Голубая мечеть",
    icon: "🕌",
    description: "В самом центре шумного города живёт удивительное спокойствие.\n\nТы открыл место, где разные культуры встречаются в гармонии.",
    city: "Ереван",
    country: "Армения",
    latitude: 40.1761,
    longitude: 44.5054,
    rarity: "legendary",
    xp: 50,
    discoveryRadiusMeters: 190,
    imagePath: "/uploads/places/blue-mosque.jpg",
    sortOrder: 90,
  },
  {
    id: "vernissage",
    name: "Вернисаж",
    icon: "🎨",
    description: "Каждая картина здесь рассказывает чью-то историю.\n\nСегодня к этим историям добавилась ещё одна — твоя.",
    city: "Ереван",
    country: "Армения",
    latitude: 40.1777,
    longitude: 44.5179,
    rarity: "legendary",
    xp: 50,
    discoveryRadiusMeters: 210,
    imagePath: "/uploads/places/vernissage.jpg",
    sortOrder: 100,
  },
];

export const DEFAULT_PUBLIC_CONFIG = {
  welcomeTitle: "Мир ждёт тебя.",
  revealRadiusMeters: 105,
  trailLifetimeSeconds: 50,
  dailyJourneyHour: 18,
  fogOpacity: 0.82,
  testCode: "1111",
  appStage: "mvp-stage3",
};
